site_name: Wetboek van Nieuweveen
site_description: Officiële wet- en regelgeving van de gemeente Nieuweveen
site_url: https://wetboek.nieuweveen.com

theme:
  name: material
  language: nl
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/nieuweveen
  generator: true

copyright: Copyright &copy; 2025 Gemeente Nieuweveen